id: IDA16C889
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-1d1b
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 12:25:22.916226+00:00
last_modified: 2023-09-28 12:25:22.916231+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22899
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22899
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ས་བཅད་མཁས་པའི་ཡིད་འཕྲོག
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9957576931328012
  ocr_word_median_confidence_index: 1.0
bases:
  I4CN10330:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CN10330
      total_pages: 256
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CN10330.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9957576931328012
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
